export { default as LineIcon } from "./LineIcon";
export { default as Regular500Px } from "./svgs/regular/Brand/Regular500Px";
export { default as RegularAdobe } from "./svgs/regular/Brand/RegularAdobe";
export { default as RegularAirbnb } from "./svgs/regular/Brand/RegularAirbnb";
export { default as RegularAirtable } from "./svgs/regular/Brand/RegularAirtable";
export { default as RegularAmazon } from "./svgs/regular/Brand/RegularAmazon";
export { default as RegularAmazonOriginal } from "./svgs/regular/Brand/RegularAmazonOriginal";
export { default as RegularAmazonPay } from "./svgs/regular/Brand/RegularAmazonPay";
export { default as RegularAmex } from "./svgs/regular/Brand/RegularAmex";
export { default as RegularAndroid } from "./svgs/regular/Brand/RegularAndroid";
export { default as RegularAndroidOriginal } from "./svgs/regular/Brand/RegularAndroidOriginal";
export { default as RegularAngellist } from "./svgs/regular/Brand/RegularAngellist";
export { default as RegularAngular } from "./svgs/regular/Brand/RegularAngular";
export { default as RegularAppleBrand } from "./svgs/regular/Brand/RegularAppleBrand";
export { default as RegularAppleMusic } from "./svgs/regular/Brand/RegularAppleMusic";
export { default as RegularApplePay } from "./svgs/regular/Brand/RegularApplePay";
export { default as RegularAppStore } from "./svgs/regular/Brand/RegularAppStore";
export { default as RegularAtlassian } from "./svgs/regular/Brand/RegularAtlassian";
export { default as RegularAudi } from "./svgs/regular/Brand/RegularAudi";
export { default as RegularAws } from "./svgs/regular/Brand/RegularAws";
export { default as RegularAzure } from "./svgs/regular/Brand/RegularAzure";
export { default as RegularBehance } from "./svgs/regular/Brand/RegularBehance";
export { default as RegularBehanceOriginal } from "./svgs/regular/Brand/RegularBehanceOriginal";
export { default as RegularBitbucket } from "./svgs/regular/Brand/RegularBitbucket";
export { default as RegularBitcoin } from "./svgs/regular/Brand/RegularBitcoin";
export { default as RegularBittorrent } from "./svgs/regular/Brand/RegularBittorrent";
export { default as RegularBlogger } from "./svgs/regular/Brand/RegularBlogger";
export { default as RegularBluetoothOriginal } from "./svgs/regular/Brand/RegularBluetoothOriginal";
export { default as RegularBmw } from "./svgs/regular/Brand/RegularBmw";
export { default as RegularBootstrap } from "./svgs/regular/Brand/RegularBootstrap";
export { default as RegularBootstrap5 } from "./svgs/regular/Brand/RegularBootstrap5";
export { default as RegularBrave } from "./svgs/regular/Brand/RegularBrave";
export { default as RegularBtc } from "./svgs/regular/Brand/RegularBtc";
export { default as RegularCashApp } from "./svgs/regular/Brand/RegularCashApp";
export { default as RegularChrome } from "./svgs/regular/Brand/RegularChrome";
export { default as RegularChromecast } from "./svgs/regular/Brand/RegularChromecast";
export { default as RegularCisco } from "./svgs/regular/Brand/RegularCisco";
export { default as RegularCloudflare } from "./svgs/regular/Brand/RegularCloudflare";
export { default as RegularCodepen } from "./svgs/regular/Brand/RegularCodepen";
export { default as RegularCoinbase } from "./svgs/regular/Brand/RegularCoinbase";
export { default as RegularConnectdevelop } from "./svgs/regular/Brand/RegularConnectdevelop";
export { default as RegularCoral } from "./svgs/regular/Brand/RegularCoral";
export { default as RegularCpanel } from "./svgs/regular/Brand/RegularCpanel";
export { default as RegularCreativeCommons } from "./svgs/regular/Brand/RegularCreativeCommons";
export { default as RegularCss3 } from "./svgs/regular/Brand/RegularCss3";
export { default as RegularDev } from "./svgs/regular/Brand/RegularDev";
export { default as RegularDialogflow } from "./svgs/regular/Brand/RegularDialogflow";
export { default as RegularDigitalocean } from "./svgs/regular/Brand/RegularDigitalocean";
export { default as RegularDinersClub } from "./svgs/regular/Brand/RegularDinersClub";
export { default as RegularDiscord } from "./svgs/regular/Brand/RegularDiscord";
export { default as RegularDiscordAlt } from "./svgs/regular/Brand/RegularDiscordAlt";
export { default as RegularDiscover } from "./svgs/regular/Brand/RegularDiscover";
export { default as RegularDocker } from "./svgs/regular/Brand/RegularDocker";
export { default as RegularDribbble } from "./svgs/regular/Brand/RegularDribbble";
export { default as RegularDropbox } from "./svgs/regular/Brand/RegularDropbox";
export { default as RegularDropboxOriginal } from "./svgs/regular/Brand/RegularDropboxOriginal";
export { default as RegularDrupal } from "./svgs/regular/Brand/RegularDrupal";
export { default as RegularDrupalOriginal } from "./svgs/regular/Brand/RegularDrupalOriginal";
export { default as RegularEdge } from "./svgs/regular/Brand/RegularEdge";
export { default as RegularEnvato } from "./svgs/regular/Brand/RegularEnvato";
export { default as RegularEthereum } from "./svgs/regular/Brand/RegularEthereum";
export { default as RegularFacebook } from "./svgs/regular/Brand/RegularFacebook";
export { default as RegularFacebookFill } from "./svgs/regular/Brand/RegularFacebookFill";
export { default as RegularFacebookLine } from "./svgs/regular/Brand/RegularFacebookLine";
export { default as RegularFacebookMessenger } from "./svgs/regular/Brand/RegularFacebookMessenger";
export { default as RegularFacebookOriginal } from "./svgs/regular/Brand/RegularFacebookOriginal";
export { default as RegularFacebookOval } from "./svgs/regular/Brand/RegularFacebookOval";
export { default as RegularFacetime } from "./svgs/regular/Brand/RegularFacetime";
export { default as RegularFigma } from "./svgs/regular/Brand/RegularFigma";
export { default as RegularFirebase } from "./svgs/regular/Brand/RegularFirebase";
export { default as RegularFirefox } from "./svgs/regular/Brand/RegularFirefox";
export { default as RegularFirefoxOriginal } from "./svgs/regular/Brand/RegularFirefoxOriginal";
export { default as RegularFitbit } from "./svgs/regular/Brand/RegularFitbit";
export { default as RegularFlickr } from "./svgs/regular/Brand/RegularFlickr";
export { default as RegularFlutter } from "./svgs/regular/Brand/RegularFlutter";
export { default as RegularFord } from "./svgs/regular/Brand/RegularFord";
export { default as RegularGatsby } from "./svgs/regular/Brand/RegularGatsby";
export { default as RegularGit } from "./svgs/regular/Brand/RegularGit";
export { default as RegularGithub } from "./svgs/regular/Brand/RegularGithub";
export { default as RegularGithubOriginal } from "./svgs/regular/Brand/RegularGithubOriginal";
export { default as RegularGo } from "./svgs/regular/Brand/RegularGo";
export { default as RegularGoodreads } from "./svgs/regular/Brand/RegularGoodreads";
export { default as RegularGoogle } from "./svgs/regular/Brand/RegularGoogle";
export { default as RegularGoogleCloud } from "./svgs/regular/Brand/RegularGoogleCloud";
export { default as RegularGoogleDrive } from "./svgs/regular/Brand/RegularGoogleDrive";
export { default as RegularGoogleMeet } from "./svgs/regular/Brand/RegularGoogleMeet";
export { default as RegularGooglePay } from "./svgs/regular/Brand/RegularGooglePay";
export { default as RegularGoogleWallet } from "./svgs/regular/Brand/RegularGoogleWallet";
export { default as RegularGrammarly } from "./svgs/regular/Brand/RegularGrammarly";
export { default as RegularHackerNews } from "./svgs/regular/Brand/RegularHackerNews";
export { default as RegularHtml5 } from "./svgs/regular/Brand/RegularHtml5";
export { default as RegularImdb } from "./svgs/regular/Brand/RegularImdb";
export { default as RegularInstagram } from "./svgs/regular/Brand/RegularInstagram";
export { default as RegularInstagramFill } from "./svgs/regular/Brand/RegularInstagramFill";
export { default as RegularInstagramOriginal } from "./svgs/regular/Brand/RegularInstagramOriginal";
export { default as RegularIos } from "./svgs/regular/Brand/RegularIos";
export { default as RegularJaguar } from "./svgs/regular/Brand/RegularJaguar";
export { default as RegularJamstack } from "./svgs/regular/Brand/RegularJamstack";
export { default as RegularJava } from "./svgs/regular/Brand/RegularJava";
export { default as RegularJavascript } from "./svgs/regular/Brand/RegularJavascript";
export { default as RegularJcb } from "./svgs/regular/Brand/RegularJcb";
export { default as RegularJoomla } from "./svgs/regular/Brand/RegularJoomla";
export { default as RegularJoomlaOriginal } from "./svgs/regular/Brand/RegularJoomlaOriginal";
export { default as RegularJsfiddle } from "./svgs/regular/Brand/RegularJsfiddle";
export { default as RegularKubernetes } from "./svgs/regular/Brand/RegularKubernetes";
export { default as RegularLaravel } from "./svgs/regular/Brand/RegularLaravel";
export { default as RegularLine } from "./svgs/regular/Brand/RegularLine";
export { default as RegularLineicons } from "./svgs/regular/Brand/RegularLineicons";
export { default as RegularLineiconsAlt } from "./svgs/regular/Brand/RegularLineiconsAlt";
export { default as RegularLineiconsSymbol } from "./svgs/regular/Brand/RegularLineiconsSymbol";
export { default as RegularLineiconsSymbolAlt } from "./svgs/regular/Brand/RegularLineiconsSymbolAlt";
export { default as RegularLineiconsSymbolAlt2 } from "./svgs/regular/Brand/RegularLineiconsSymbolAlt2";
export { default as RegularLinkedin } from "./svgs/regular/Brand/RegularLinkedin";
export { default as RegularLinkedinOriginal } from "./svgs/regular/Brand/RegularLinkedinOriginal";
export { default as RegularMagento } from "./svgs/regular/Brand/RegularMagento";
export { default as RegularMailchimp } from "./svgs/regular/Brand/RegularMailchimp";
export { default as RegularMarkdown } from "./svgs/regular/Brand/RegularMarkdown";
export { default as RegularMastercard } from "./svgs/regular/Brand/RegularMastercard";
export { default as RegularMedium } from "./svgs/regular/Brand/RegularMedium";
export { default as RegularMediumAlt } from "./svgs/regular/Brand/RegularMediumAlt";
export { default as RegularMercedes } from "./svgs/regular/Brand/RegularMercedes";
export { default as RegularMeta } from "./svgs/regular/Brand/RegularMeta";
export { default as RegularMeta1 } from "./svgs/regular/Brand/RegularMeta1";
export { default as RegularMeta2 } from "./svgs/regular/Brand/RegularMeta2";
export { default as RegularMicrosoft } from "./svgs/regular/Brand/RegularMicrosoft";
export { default as RegularMicrosoftEdge } from "./svgs/regular/Brand/RegularMicrosoftEdge";
export { default as RegularMicrosoftTeams } from "./svgs/regular/Brand/RegularMicrosoftTeams";
export { default as RegularMongodb } from "./svgs/regular/Brand/RegularMongodb";
export { default as RegularMysql } from "./svgs/regular/Brand/RegularMysql";
export { default as RegularNetflix } from "./svgs/regular/Brand/RegularNetflix";
export { default as RegularNetlify } from "./svgs/regular/Brand/RegularNetlify";
export { default as RegularNextjs } from "./svgs/regular/Brand/RegularNextjs";
export { default as RegularNissan } from "./svgs/regular/Brand/RegularNissan";
export { default as RegularNodejs } from "./svgs/regular/Brand/RegularNodejs";
export { default as RegularNodejsAlt } from "./svgs/regular/Brand/RegularNodejsAlt";
export { default as RegularNotion } from "./svgs/regular/Brand/RegularNotion";
export { default as RegularNpm } from "./svgs/regular/Brand/RegularNpm";
export { default as RegularOculus } from "./svgs/regular/Brand/RegularOculus";
export { default as RegularOpera } from "./svgs/regular/Brand/RegularOpera";
export { default as RegularPaddle } from "./svgs/regular/Brand/RegularPaddle";
export { default as RegularPatreon } from "./svgs/regular/Brand/RegularPatreon";
export { default as RegularPaypal } from "./svgs/regular/Brand/RegularPaypal";
export { default as RegularPaypalOriginal } from "./svgs/regular/Brand/RegularPaypalOriginal";
export { default as RegularPhp } from "./svgs/regular/Brand/RegularPhp";
export { default as RegularPinterest } from "./svgs/regular/Brand/RegularPinterest";
export { default as RegularPlaystation } from "./svgs/regular/Brand/RegularPlaystation";
export { default as RegularPlayStore } from "./svgs/regular/Brand/RegularPlayStore";
export { default as RegularPlayStoreAlt } from "./svgs/regular/Brand/RegularPlayStoreAlt";
export { default as RegularPlayStoreFill } from "./svgs/regular/Brand/RegularPlayStoreFill";
export { default as RegularPostgresql } from "./svgs/regular/Brand/RegularPostgresql";
export { default as RegularPostman } from "./svgs/regular/Brand/RegularPostman";
export { default as RegularProducthunt } from "./svgs/regular/Brand/RegularProducthunt";
export { default as RegularPython } from "./svgs/regular/Brand/RegularPython";
export { default as RegularQuora } from "./svgs/regular/Brand/RegularQuora";
export { default as RegularReact } from "./svgs/regular/Brand/RegularReact";
export { default as RegularReddit } from "./svgs/regular/Brand/RegularReddit";
export { default as RegularSafari } from "./svgs/regular/Brand/RegularSafari";
export { default as RegularShopify } from "./svgs/regular/Brand/RegularShopify";
export { default as RegularSignalApp } from "./svgs/regular/Brand/RegularSignalApp";
export { default as RegularSketch } from "./svgs/regular/Brand/RegularSketch";
export { default as RegularSkype } from "./svgs/regular/Brand/RegularSkype";
export { default as RegularSlack } from "./svgs/regular/Brand/RegularSlack";
export { default as RegularSlackLine } from "./svgs/regular/Brand/RegularSlackLine";
export { default as RegularSlideshare } from "./svgs/regular/Brand/RegularSlideshare";
export { default as RegularSnapchat } from "./svgs/regular/Brand/RegularSnapchat";
export { default as RegularSoundcloud } from "./svgs/regular/Brand/RegularSoundcloud";
export { default as RegularSoundcloudOriginal } from "./svgs/regular/Brand/RegularSoundcloudOriginal";
export { default as RegularSpotify } from "./svgs/regular/Brand/RegularSpotify";
export { default as RegularSpotifyOriginal } from "./svgs/regular/Brand/RegularSpotifyOriginal";
export { default as RegularSquarespace } from "./svgs/regular/Brand/RegularSquarespace";
export { default as RegularStackoverflow } from "./svgs/regular/Brand/RegularStackoverflow";
export { default as RegularSteam } from "./svgs/regular/Brand/RegularSteam";
export { default as RegularStripe } from "./svgs/regular/Brand/RegularStripe";
export { default as RegularStumbleupon } from "./svgs/regular/Brand/RegularStumbleupon";
export { default as RegularSvelte } from "./svgs/regular/Brand/RegularSvelte";
export { default as RegularSwift } from "./svgs/regular/Brand/RegularSwift";
export { default as RegularTailwindcss } from "./svgs/regular/Brand/RegularTailwindcss";
export { default as RegularTelegram } from "./svgs/regular/Brand/RegularTelegram";
export { default as RegularTelegramOriginal } from "./svgs/regular/Brand/RegularTelegramOriginal";
export { default as RegularTesla } from "./svgs/regular/Brand/RegularTesla";
export { default as RegularTiktok } from "./svgs/regular/Brand/RegularTiktok";
export { default as RegularTiktokAlt } from "./svgs/regular/Brand/RegularTiktokAlt";
export { default as RegularToyota } from "./svgs/regular/Brand/RegularToyota";
export { default as RegularTrello } from "./svgs/regular/Brand/RegularTrello";
export { default as RegularTumblr } from "./svgs/regular/Brand/RegularTumblr";
export { default as RegularTwitch } from "./svgs/regular/Brand/RegularTwitch";
export { default as RegularTwitter } from "./svgs/regular/Brand/RegularTwitter";
export { default as RegularTwitterFill } from "./svgs/regular/Brand/RegularTwitterFill";
export { default as RegularTwitterOriginal } from "./svgs/regular/Brand/RegularTwitterOriginal";
export { default as RegularTypescript } from "./svgs/regular/Brand/RegularTypescript";
export { default as RegularUbuntu } from "./svgs/regular/Brand/RegularUbuntu";
export { default as RegularUnsplash } from "./svgs/regular/Brand/RegularUnsplash";
export { default as RegularVercel } from "./svgs/regular/Brand/RegularVercel";
export { default as RegularVimeo } from "./svgs/regular/Brand/RegularVimeo";
export { default as RegularVisa } from "./svgs/regular/Brand/RegularVisa";
export { default as RegularVk } from "./svgs/regular/Brand/RegularVk";
export { default as RegularVmware } from "./svgs/regular/Brand/RegularVmware";
export { default as RegularVolkswagen } from "./svgs/regular/Brand/RegularVolkswagen";
export { default as RegularVsCode } from "./svgs/regular/Brand/RegularVsCode";
export { default as RegularVuejs } from "./svgs/regular/Brand/RegularVuejs";
export { default as RegularWebhooks } from "./svgs/regular/Brand/RegularWebhooks";
export { default as RegularWechat } from "./svgs/regular/Brand/RegularWechat";
export { default as RegularWhatsapp } from "./svgs/regular/Brand/RegularWhatsapp";
export { default as RegularWindows } from "./svgs/regular/Brand/RegularWindows";
export { default as RegularWordpress } from "./svgs/regular/Brand/RegularWordpress";
export { default as RegularWordpressFill } from "./svgs/regular/Brand/RegularWordpressFill";
export { default as RegularXbox } from "./svgs/regular/Brand/RegularXbox";
export { default as RegularXrp } from "./svgs/regular/Brand/RegularXrp";
export { default as RegularYahoo } from "./svgs/regular/Brand/RegularYahoo";
export { default as RegularYcombinator } from "./svgs/regular/Brand/RegularYcombinator";
export { default as RegularYoutube } from "./svgs/regular/Brand/RegularYoutube";
export { default as RegularZapier } from "./svgs/regular/Brand/RegularZapier";
export { default as RegularZoom } from "./svgs/regular/Brand/RegularZoom";
export { default as RegularAgenda } from "./svgs/regular/Business/RegularAgenda";
export { default as RegularApartment } from "./svgs/regular/Business/RegularApartment";
export { default as RegularBriefcaseAlt } from "./svgs/regular/Business/RegularBriefcaseAlt";
export { default as RegularCart } from "./svgs/regular/Business/RegularCart";
export { default as RegularCartFull } from "./svgs/regular/Business/RegularCartFull";
export { default as RegularConsulting } from "./svgs/regular/Business/RegularConsulting";
export { default as RegularCustomer } from "./svgs/regular/Business/RegularCustomer";
export { default as RegularDelivery } from "./svgs/regular/Business/RegularDelivery";
export { default as RegularGrow } from "./svgs/regular/Business/RegularGrow";
export { default as RegularHandshake } from "./svgs/regular/Business/RegularHandshake";
export { default as RegularInvestment } from "./svgs/regular/Business/RegularInvestment";
export { default as RegularInvestMonitor } from "./svgs/regular/Business/RegularInvestMonitor";
export { default as RegularLicense } from "./svgs/regular/Business/RegularLicense";
export { default as RegularNotepad } from "./svgs/regular/Business/RegularNotepad";
export { default as RegularOffer } from "./svgs/regular/Business/RegularOffer";
export { default as RegularPaperclip } from "./svgs/regular/Business/RegularPaperclip";
export { default as RegularPieChart } from "./svgs/regular/Business/RegularPieChart";
export { default as RegularPin } from "./svgs/regular/Business/RegularPin";
export { default as RegularQuotation } from "./svgs/regular/Business/RegularQuotation";
export { default as RegularRevenue } from "./svgs/regular/Business/RegularRevenue";
export { default as RegularStamp } from "./svgs/regular/Business/RegularStamp";
export { default as RegularStatsDown } from "./svgs/regular/Business/RegularStatsDown";
export { default as RegularStatsUp } from "./svgs/regular/Business/RegularStatsUp";
export { default as RegularTag } from "./svgs/regular/Business/RegularTag";
export { default as RegularTarget } from "./svgs/regular/Business/RegularTarget";
export { default as RegularTargetRevenue } from "./svgs/regular/Business/RegularTargetRevenue";
export { default as RegularAnchor } from "./svgs/regular/Communication/RegularAnchor";
export { default as RegularBiCycle } from "./svgs/regular/Communication/RegularBiCycle";
export { default as RegularBridge } from "./svgs/regular/Communication/RegularBridge";
export { default as RegularBubble } from "./svgs/regular/Communication/RegularBubble";
export { default as RegularBullhorn } from "./svgs/regular/Communication/RegularBullhorn";
export { default as RegularBus } from "./svgs/regular/Communication/RegularBus";
export { default as RegularCar } from "./svgs/regular/Communication/RegularCar";
export { default as RegularCarAlt } from "./svgs/regular/Communication/RegularCarAlt";
export { default as RegularCaravan } from "./svgs/regular/Communication/RegularCaravan";
export { default as RegularComments } from "./svgs/regular/Communication/RegularComments";
export { default as RegularCommentsAlt2 } from "./svgs/regular/Communication/RegularCommentsAlt2";
export { default as RegularCommentsReply } from "./svgs/regular/Communication/RegularCommentsReply";
export { default as RegularEnvelope } from "./svgs/regular/Communication/RegularEnvelope";
export { default as RegularHelicopter } from "./svgs/regular/Communication/RegularHelicopter";
export { default as RegularInbox } from "./svgs/regular/Communication/RegularInbox";
export { default as RegularPhone } from "./svgs/regular/Communication/RegularPhone";
export { default as RegularPhoneSet } from "./svgs/regular/Communication/RegularPhoneSet";
export { default as RegularPlane } from "./svgs/regular/Communication/RegularPlane";
export { default as RegularPopup } from "./svgs/regular/Communication/RegularPopup";
export { default as RegularPostcard } from "./svgs/regular/Communication/RegularPostcard";
export { default as RegularReply } from "./svgs/regular/Communication/RegularReply";
export { default as RegularRoad } from "./svgs/regular/Communication/RegularRoad";
export { default as RegularScooter } from "./svgs/regular/Communication/RegularScooter";
export { default as RegularShip } from "./svgs/regular/Communication/RegularShip";
export { default as RegularSupport } from "./svgs/regular/Communication/RegularSupport";
export { default as RegularTaxi } from "./svgs/regular/Communication/RegularTaxi";
export { default as RegularTrain } from "./svgs/regular/Communication/RegularTrain";
export { default as RegularTrainAlt } from "./svgs/regular/Communication/RegularTrainAlt";
export { default as RegularBricks } from "./svgs/regular/Construction/RegularBricks";
export { default as RegularConstruction } from "./svgs/regular/Construction/RegularConstruction";
export { default as RegularConstructionHammer } from "./svgs/regular/Construction/RegularConstructionHammer";
export { default as RegularHammer } from "./svgs/regular/Construction/RegularHammer";
export { default as RegularHelmet } from "./svgs/regular/Construction/RegularHelmet";
export { default as RegularPaintBucketAlt } from "./svgs/regular/Construction/RegularPaintBucketAlt";
export { default as RegularPaintRoller } from "./svgs/regular/Construction/RegularPaintRoller";
export { default as RegularRuler } from "./svgs/regular/Construction/RegularRuler";
export { default as RegularRulerAlt } from "./svgs/regular/Construction/RegularRulerAlt";
export { default as RegularRulerPencil } from "./svgs/regular/Construction/RegularRulerPencil";
export { default as RegularShovel } from "./svgs/regular/Construction/RegularShovel";
export { default as RegularTrowel } from "./svgs/regular/Construction/RegularTrowel";
export { default as RegularWheelbarrow } from "./svgs/regular/Construction/RegularWheelbarrow";
export { default as RegularCalculator } from "./svgs/regular/Currency/RegularCalculator";
export { default as RegularCalculatorAlt } from "./svgs/regular/Currency/RegularCalculatorAlt";
export { default as RegularCoin } from "./svgs/regular/Currency/RegularCoin";
export { default as RegularCreditCards } from "./svgs/regular/Currency/RegularCreditCards";
export { default as RegularDiamondAlt } from "./svgs/regular/Currency/RegularDiamondAlt";
export { default as RegularDiamondShape } from "./svgs/regular/Currency/RegularDiamondShape";
export { default as RegularDollar } from "./svgs/regular/Currency/RegularDollar";
export { default as RegularEuro } from "./svgs/regular/Currency/RegularEuro";
export { default as RegularMoneyLocation } from "./svgs/regular/Currency/RegularMoneyLocation";
export { default as RegularMoneyProtection } from "./svgs/regular/Currency/RegularMoneyProtection";
export { default as RegularPound } from "./svgs/regular/Currency/RegularPound";
export { default as RegularRupee } from "./svgs/regular/Currency/RegularRupee";
export { default as RegularWallet } from "./svgs/regular/Currency/RegularWallet";
export { default as RegularYen } from "./svgs/regular/Currency/RegularYen";
export { default as RegularBrush } from "./svgs/regular/Design/RegularBrush";
export { default as RegularBrushAlt } from "./svgs/regular/Design/RegularBrushAlt";
export { default as RegularCrop } from "./svgs/regular/Design/RegularCrop";
export { default as RegularGrid } from "./svgs/regular/Design/RegularGrid";
export { default as RegularGridAlt } from "./svgs/regular/Design/RegularGridAlt";
export { default as RegularHighlight } from "./svgs/regular/Design/RegularHighlight";
export { default as RegularHighlightAlt } from "./svgs/regular/Design/RegularHighlightAlt";
export { default as RegularLayers } from "./svgs/regular/Design/RegularLayers";
export { default as RegularLayout } from "./svgs/regular/Design/RegularLayout";
export { default as RegularMove } from "./svgs/regular/Design/RegularMove";
export { default as RegularPallet } from "./svgs/regular/Design/RegularPallet";
export { default as RegularSelectCursor } from "./svgs/regular/Design/RegularSelectCursor";
export { default as RegularSlice } from "./svgs/regular/Design/RegularSlice";
export { default as RegularUx } from "./svgs/regular/Design/RegularUx";
export { default as RegularVector } from "./svgs/regular/Design/RegularVector";
export { default as RegularAngleDoubleDown } from "./svgs/regular/Direction/RegularAngleDoubleDown";
export { default as RegularAngleDoubleLeft } from "./svgs/regular/Direction/RegularAngleDoubleLeft";
export { default as RegularAngleDoubleRight } from "./svgs/regular/Direction/RegularAngleDoubleRight";
export { default as RegularAngleDoubleUp } from "./svgs/regular/Direction/RegularAngleDoubleUp";
export { default as RegularArrowDown } from "./svgs/regular/Direction/RegularArrowDown";
export { default as RegularArrowDownCircle } from "./svgs/regular/Direction/RegularArrowDownCircle";
export { default as RegularArrowLeft } from "./svgs/regular/Direction/RegularArrowLeft";
export { default as RegularArrowLeftCircle } from "./svgs/regular/Direction/RegularArrowLeftCircle";
export { default as RegularArrowRight } from "./svgs/regular/Direction/RegularArrowRight";
export { default as RegularArrowRightCircle } from "./svgs/regular/Direction/RegularArrowRightCircle";
export { default as RegularArrowsHorizontal } from "./svgs/regular/Direction/RegularArrowsHorizontal";
export { default as RegularArrowsVertical } from "./svgs/regular/Direction/RegularArrowsVertical";
export { default as RegularArrowTopLeft } from "./svgs/regular/Direction/RegularArrowTopLeft";
export { default as RegularArrowTopRight } from "./svgs/regular/Direction/RegularArrowTopRight";
export { default as RegularArrowUp } from "./svgs/regular/Direction/RegularArrowUp";
export { default as RegularArrowUpCircle } from "./svgs/regular/Direction/RegularArrowUpCircle";
export { default as RegularChevronDown } from "./svgs/regular/Direction/RegularChevronDown";
export { default as RegularChevronDownCircle } from "./svgs/regular/Direction/RegularChevronDownCircle";
export { default as RegularChevronLeft } from "./svgs/regular/Direction/RegularChevronLeft";
export { default as RegularChevronLeftCircle } from "./svgs/regular/Direction/RegularChevronLeftCircle";
export { default as RegularChevronRight } from "./svgs/regular/Direction/RegularChevronRight";
export { default as RegularChevronRightCircle } from "./svgs/regular/Direction/RegularChevronRightCircle";
export { default as RegularChevronUp } from "./svgs/regular/Direction/RegularChevronUp";
export { default as RegularChevronUpCircle } from "./svgs/regular/Direction/RegularChevronUpCircle";
export { default as RegularDirection } from "./svgs/regular/Direction/RegularDirection";
export { default as RegularDirectionAlt } from "./svgs/regular/Direction/RegularDirectionAlt";
export { default as RegularDirectionLtr } from "./svgs/regular/Direction/RegularDirectionLtr";
export { default as RegularDirectionRtl } from "./svgs/regular/Direction/RegularDirectionRtl";
export { default as RegularEnter } from "./svgs/regular/Direction/RegularEnter";
export { default as RegularExit } from "./svgs/regular/Direction/RegularExit";
export { default as RegularExitDown } from "./svgs/regular/Direction/RegularExitDown";
export { default as RegularExitUp } from "./svgs/regular/Direction/RegularExitUp";
export { default as RegularPointerDown } from "./svgs/regular/Direction/RegularPointerDown";
export { default as RegularPointerLeft } from "./svgs/regular/Direction/RegularPointerLeft";
export { default as RegularPointerRight } from "./svgs/regular/Direction/RegularPointerRight";
export { default as RegularPointerTop } from "./svgs/regular/Direction/RegularPointerTop";
export { default as RegularShiftLeft } from "./svgs/regular/Direction/RegularShiftLeft";
export { default as RegularShiftRight } from "./svgs/regular/Direction/RegularShiftRight";
export { default as RegularBlackboard } from "./svgs/regular/Education/RegularBlackboard";
export { default as RegularBook } from "./svgs/regular/Education/RegularBook";
export { default as RegularCertificate } from "./svgs/regular/Education/RegularCertificate";
export { default as RegularClipboard } from "./svgs/regular/Education/RegularClipboard";
export { default as RegularCompass } from "./svgs/regular/Education/RegularCompass";
export { default as RegularEraser } from "./svgs/regular/Education/RegularEraser";
export { default as RegularGraduation } from "./svgs/regular/Education/RegularGraduation";
export { default as RegularLibrary } from "./svgs/regular/Education/RegularLibrary";
export { default as RegularPencil } from "./svgs/regular/Education/RegularPencil";
export { default as RegularPencilAlt } from "./svgs/regular/Education/RegularPencilAlt";
export { default as RegularSchoolBench } from "./svgs/regular/Education/RegularSchoolBench";
export { default as RegularSchoolBenchAlt } from "./svgs/regular/Education/RegularSchoolBenchAlt";
export { default as RegularWorld } from "./svgs/regular/Education/RegularWorld";
export { default as RegularWorldAlt } from "./svgs/regular/Education/RegularWorldAlt";
export { default as RegularWrite } from "./svgs/regular/Education/RegularWrite";
export { default as RegularBurger } from "./svgs/regular/Food and Restaurant/RegularBurger";
export { default as RegularChefHat } from "./svgs/regular/Food and Restaurant/RegularChefHat";
export { default as RegularCoffeeCup } from "./svgs/regular/Food and Restaurant/RegularCoffeeCup";
export { default as RegularDinner } from "./svgs/regular/Food and Restaurant/RegularDinner";
export { default as RegularFreshJuice } from "./svgs/regular/Food and Restaurant/RegularFreshJuice";
export { default as RegularJuice } from "./svgs/regular/Food and Restaurant/RegularJuice";
export { default as RegularPizza } from "./svgs/regular/Food and Restaurant/RegularPizza";
export { default as RegularRestaurant } from "./svgs/regular/Food and Restaurant/RegularRestaurant";
export { default as RegularService } from "./svgs/regular/Food and Restaurant/RegularService";
export { default as RegularAmbulance } from "./svgs/regular/Health and Medical/RegularAmbulance";
export { default as RegularBasketball } from "./svgs/regular/Health and Medical/RegularBasketball";
export { default as RegularCapsule } from "./svgs/regular/Health and Medical/RegularCapsule";
export { default as RegularDumbbell } from "./svgs/regular/Health and Medical/RegularDumbbell";
export { default as RegularFirstAid } from "./svgs/regular/Health and Medical/RegularFirstAid";
export { default as RegularHeartMonitor } from "./svgs/regular/Health and Medical/RegularHeartMonitor";
export { default as RegularHospital } from "./svgs/regular/Health and Medical/RegularHospital";
export { default as RegularMicroscope } from "./svgs/regular/Health and Medical/RegularMicroscope";
export { default as RegularPulse } from "./svgs/regular/Health and Medical/RegularPulse";
export { default as RegularSkippingRope } from "./svgs/regular/Health and Medical/RegularSkippingRope";
export { default as RegularSlim } from "./svgs/regular/Health and Medical/RegularSlim";
export { default as RegularSthethoscope } from "./svgs/regular/Health and Medical/RegularSthethoscope";
export { default as RegularSyringe } from "./svgs/regular/Health and Medical/RegularSyringe";
export { default as RegularWeight } from "./svgs/regular/Health and Medical/RegularWeight";
export { default as RegularWheelchair } from "./svgs/regular/Health and Medical/RegularWheelchair";
export { default as RegularBolt } from "./svgs/regular/Interface and Sign/RegularBolt";
export { default as RegularBoltAlt } from "./svgs/regular/Interface and Sign/RegularBoltAlt";
export { default as RegularCheckBox } from "./svgs/regular/Interface and Sign/RegularCheckBox";
export { default as RegularCheckmark } from "./svgs/regular/Interface and Sign/RegularCheckmark";
export { default as RegularCheckmarkCircle } from "./svgs/regular/Interface and Sign/RegularCheckmarkCircle";
export { default as RegularCircleMinus } from "./svgs/regular/Interface and Sign/RegularCircleMinus";
export { default as RegularCirclePlus } from "./svgs/regular/Interface and Sign/RegularCirclePlus";
export { default as RegularClose } from "./svgs/regular/Interface and Sign/RegularClose";
export { default as RegularCrossCircle } from "./svgs/regular/Interface and Sign/RegularCrossCircle";
export { default as RegularEye } from "./svgs/regular/Interface and Sign/RegularEye";
export { default as RegularFlag } from "./svgs/regular/Interface and Sign/RegularFlag";
export { default as RegularFlagAlt } from "./svgs/regular/Interface and Sign/RegularFlagAlt";
export { default as RegularFunnel } from "./svgs/regular/Interface and Sign/RegularFunnel";
export { default as RegularHand } from "./svgs/regular/Interface and Sign/RegularHand";
export { default as RegularHeart } from "./svgs/regular/Interface and Sign/RegularHeart";
export { default as RegularHeartFill } from "./svgs/regular/Interface and Sign/RegularHeartFill";
export { default as RegularHelp } from "./svgs/regular/Interface and Sign/RegularHelp";
export { default as RegularInfinite } from "./svgs/regular/Interface and Sign/RegularInfinite";
export { default as RegularInformation } from "./svgs/regular/Interface and Sign/RegularInformation";
export { default as RegularInvention } from "./svgs/regular/Interface and Sign/RegularInvention";
export { default as RegularKey } from "./svgs/regular/Interface and Sign/RegularKey";
export { default as RegularLifering } from "./svgs/regular/Interface and Sign/RegularLifering";
export { default as RegularList } from "./svgs/regular/Interface and Sign/RegularList";
export { default as RegularLock } from "./svgs/regular/Interface and Sign/RegularLock";
export { default as RegularLockAlt } from "./svgs/regular/Interface and Sign/RegularLockAlt";
export { default as RegularMinus } from "./svgs/regular/Interface and Sign/RegularMinus";
export { default as RegularMore } from "./svgs/regular/Interface and Sign/RegularMore";
export { default as RegularMoreAlt } from "./svgs/regular/Interface and Sign/RegularMoreAlt";
export { default as RegularMusic } from "./svgs/regular/Interface and Sign/RegularMusic";
export { default as RegularPlus } from "./svgs/regular/Interface and Sign/RegularPlus";
export { default as RegularPointer } from "./svgs/regular/Interface and Sign/RegularPointer";
export { default as RegularPowerSwitch } from "./svgs/regular/Interface and Sign/RegularPowerSwitch";
export { default as RegularProtection } from "./svgs/regular/Interface and Sign/RegularProtection";
export { default as RegularQuestionCircle } from "./svgs/regular/Interface and Sign/RegularQuestionCircle";
export { default as RegularRadioButton } from "./svgs/regular/Interface and Sign/RegularRadioButton";
export { default as RegularShield } from "./svgs/regular/Interface and Sign/RegularShield";
export { default as RegularTeabag } from "./svgs/regular/Interface and Sign/RegularTeabag";
export { default as RegularThumbsDown } from "./svgs/regular/Interface and Sign/RegularThumbsDown";
export { default as RegularThumbsUp } from "./svgs/regular/Interface and Sign/RegularThumbsUp";
export { default as RegularTicket } from "./svgs/regular/Interface and Sign/RegularTicket";
export { default as RegularTicketAlt } from "./svgs/regular/Interface and Sign/RegularTicketAlt";
export { default as RegularUnlock } from "./svgs/regular/Interface and Sign/RegularUnlock";
export { default as RegularWarning } from "./svgs/regular/Interface and Sign/RegularWarning";
export { default as RegularBarChart } from "./svgs/regular/Marketing/RegularBarChart";
export { default as RegularGraph } from "./svgs/regular/Marketing/RegularGraph";
export { default as RegularKeywordResearch } from "./svgs/regular/Marketing/RegularKeywordResearch";
export { default as RegularNetwork } from "./svgs/regular/Marketing/RegularNetwork";
export { default as RegularSeo } from "./svgs/regular/Marketing/RegularSeo";
export { default as RegularTargetCustomer } from "./svgs/regular/Marketing/RegularTargetCustomer";
export { default as RegularBackward } from "./svgs/regular/Media/RegularBackward";
export { default as RegularForward } from "./svgs/regular/Media/RegularForward";
export { default as RegularFrameExpand } from "./svgs/regular/Media/RegularFrameExpand";
export { default as RegularFullScreen } from "./svgs/regular/Media/RegularFullScreen";
export { default as RegularGallery } from "./svgs/regular/Media/RegularGallery";
export { default as RegularPause } from "./svgs/regular/Media/RegularPause";
export { default as RegularPlay } from "./svgs/regular/Media/RegularPlay";
export { default as RegularShuffle } from "./svgs/regular/Media/RegularShuffle";
export { default as RegularStop } from "./svgs/regular/Media/RegularStop";
export { default as RegularVideo } from "./svgs/regular/Media/RegularVideo";
export { default as RegularVolume } from "./svgs/regular/Media/RegularVolume";
export { default as RegularVolumeHigh } from "./svgs/regular/Media/RegularVolumeHigh";
export { default as RegularVolumeLow } from "./svgs/regular/Media/RegularVolumeLow";
export { default as RegularVolumeMedium } from "./svgs/regular/Media/RegularVolumeMedium";
export { default as RegularVolumeMute } from "./svgs/regular/Media/RegularVolumeMute";
export { default as RegularBug } from "./svgs/regular/Nature/RegularBug";
export { default as RegularFlower } from "./svgs/regular/Nature/RegularFlower";
export { default as RegularIsland } from "./svgs/regular/Nature/RegularIsland";
export { default as RegularLeaf } from "./svgs/regular/Nature/RegularLeaf";
export { default as RegularMashroom } from "./svgs/regular/Nature/RegularMashroom";
export { default as RegularMushroom } from "./svgs/regular/Nature/RegularMushroom";
export { default as RegularSprout } from "./svgs/regular/Nature/RegularSprout";
export { default as RegularTree } from "./svgs/regular/Nature/RegularTree";
export { default as RegularTrees } from "./svgs/regular/Nature/RegularTrees";
export { default as RegularBaloon } from "./svgs/regular/Party and Fest/RegularBaloon";
export { default as RegularCake } from "./svgs/regular/Party and Fest/RegularCake";
export { default as RegularCandy } from "./svgs/regular/Party and Fest/RegularCandy";
export { default as RegularCandyCane } from "./svgs/regular/Party and Fest/RegularCandyCane";
export { default as RegularFireworks } from "./svgs/regular/Party and Fest/RegularFireworks";
export { default as RegularFlagsAlt1 } from "./svgs/regular/Party and Fest/RegularFlagsAlt1";
export { default as RegularSpray } from "./svgs/regular/Party and Fest/RegularSpray";
export { default as RegularBriefcase } from "./svgs/regular/Personal/RegularBriefcase";
export { default as RegularCrown } from "./svgs/regular/Personal/RegularCrown";
export { default as RegularCup } from "./svgs/regular/Personal/RegularCup";
export { default as RegularGift } from "./svgs/regular/Personal/RegularGift";
export { default as RegularHome } from "./svgs/regular/Personal/RegularHome";
export { default as RegularThought } from "./svgs/regular/Personal/RegularThought";
export { default as RegularTShirt } from "./svgs/regular/Personal/RegularTShirt";
export { default as RegularCool } from "./svgs/regular/Smileys/RegularCool";
export { default as RegularFriendly } from "./svgs/regular/Smileys/RegularFriendly";
export { default as RegularHappy } from "./svgs/regular/Smileys/RegularHappy";
export { default as RegularSad } from "./svgs/regular/Smileys/RegularSad";
export { default as RegularSmile } from "./svgs/regular/Smileys/RegularSmile";
export { default as RegularSpeechless } from "./svgs/regular/Smileys/RegularSpeechless";
export { default as RegularSuspect } from "./svgs/regular/Smileys/RegularSuspect";
export { default as RegularTounge } from "./svgs/regular/Smileys/RegularTounge";
export { default as RegularHourglass } from "./svgs/regular/Spinner/RegularHourglass";
export { default as RegularSpinner } from "./svgs/regular/Spinner/RegularSpinner";
export { default as RegularSpinnerArrow } from "./svgs/regular/Spinner/RegularSpinnerArrow";
export { default as RegularSpinnerSolid } from "./svgs/regular/Spinner/RegularSpinnerSolid";
export { default as RegularBold } from "./svgs/regular/Text Editor/RegularBold";
export { default as RegularIndentDecrease } from "./svgs/regular/Text Editor/RegularIndentDecrease";
export { default as RegularIndentIncrease } from "./svgs/regular/Text Editor/RegularIndentIncrease";
export { default as RegularItalic } from "./svgs/regular/Text Editor/RegularItalic";
export { default as RegularLineDashed } from "./svgs/regular/Text Editor/RegularLineDashed";
export { default as RegularLineDotted } from "./svgs/regular/Text Editor/RegularLineDotted";
export { default as RegularLineDouble } from "./svgs/regular/Text Editor/RegularLineDouble";
export { default as RegularLineSpacing } from "./svgs/regular/Text Editor/RegularLineSpacing";
export { default as RegularPageBreak } from "./svgs/regular/Text Editor/RegularPageBreak";
export { default as RegularPagination } from "./svgs/regular/Text Editor/RegularPagination";
export { default as RegularPilcrow } from "./svgs/regular/Text Editor/RegularPilcrow";
export { default as RegularSortAlphaAsc } from "./svgs/regular/Text Editor/RegularSortAlphaAsc";
export { default as RegularSortAmountAsc } from "./svgs/regular/Text Editor/RegularSortAmountAsc";
export { default as RegularSortAmountDsc } from "./svgs/regular/Text Editor/RegularSortAmountDsc";
export { default as RegularSpellcheck } from "./svgs/regular/Text Editor/RegularSpellcheck";
export { default as RegularStrikethrough } from "./svgs/regular/Text Editor/RegularStrikethrough";
export { default as RegularTextAlignCenter } from "./svgs/regular/Text Editor/RegularTextAlignCenter";
export { default as RegularTextAlignJustify } from "./svgs/regular/Text Editor/RegularTextAlignJustify";
export { default as RegularTextAlignLeft } from "./svgs/regular/Text Editor/RegularTextAlignLeft";
export { default as RegularTextAlignRight } from "./svgs/regular/Text Editor/RegularTextAlignRight";
export { default as RegularTextFormat } from "./svgs/regular/Text Editor/RegularTextFormat";
export { default as RegularTextFormatRemove } from "./svgs/regular/Text Editor/RegularTextFormatRemove";
export { default as RegularUnderline } from "./svgs/regular/Text Editor/RegularUnderline";
export { default as RegularPyramids } from "./svgs/regular/Travel/RegularPyramids";
export { default as RegularSurfBoard } from "./svgs/regular/Travel/RegularSurfBoard";
export { default as RegularTravel } from "./svgs/regular/Travel/RegularTravel";
export { default as RegularCloud } from "./svgs/regular/Weather/RegularCloud";
export { default as RegularCloudySun } from "./svgs/regular/Weather/RegularCloudySun";
export { default as RegularDrop } from "./svgs/regular/Weather/RegularDrop";
export { default as RegularNight } from "./svgs/regular/Weather/RegularNight";
export { default as RegularRain } from "./svgs/regular/Weather/RegularRain";
export { default as RegularSun } from "./svgs/regular/Weather/RegularSun";
export { default as RegularThunder } from "./svgs/regular/Weather/RegularThunder";
export { default as RegularThunderAlt } from "./svgs/regular/Weather/RegularThunderAlt";
export { default as RegularAddFiles } from "./svgs/regular/Web and Technology/RegularAddFiles";
export { default as RegularAlarm } from "./svgs/regular/Web and Technology/RegularAlarm";
export { default as RegularAlarmClock } from "./svgs/regular/Web and Technology/RegularAlarmClock";
export { default as RegularArchive } from "./svgs/regular/Web and Technology/RegularArchive";
export { default as RegularBan } from "./svgs/regular/Web and Technology/RegularBan";
export { default as RegularBluetooth } from "./svgs/regular/Web and Technology/RegularBluetooth";
export { default as RegularBookmark } from "./svgs/regular/Web and Technology/RegularBookmark";
export { default as RegularBookmarkAlt } from "./svgs/regular/Web and Technology/RegularBookmarkAlt";
export { default as RegularBulb } from "./svgs/regular/Web and Technology/RegularBulb";
export { default as RegularCalendar } from "./svgs/regular/Web and Technology/RegularCalendar";
export { default as RegularCamera } from "./svgs/regular/Web and Technology/RegularCamera";
export { default as RegularCloudCheck } from "./svgs/regular/Web and Technology/RegularCloudCheck";
export { default as RegularCloudDownload } from "./svgs/regular/Web and Technology/RegularCloudDownload";
export { default as RegularCloudNetwork } from "./svgs/regular/Web and Technology/RegularCloudNetwork";
export { default as RegularCloudSync } from "./svgs/regular/Web and Technology/RegularCloudSync";
export { default as RegularCloudUpload } from "./svgs/regular/Web and Technology/RegularCloudUpload";
export { default as RegularCode } from "./svgs/regular/Web and Technology/RegularCode";
export { default as RegularCodeAlt } from "./svgs/regular/Web and Technology/RegularCodeAlt";
export { default as RegularCog } from "./svgs/regular/Web and Technology/RegularCog";
export { default as RegularCogs } from "./svgs/regular/Web and Technology/RegularCogs";
export { default as RegularControlPanel } from "./svgs/regular/Web and Technology/RegularControlPanel";
export { default as RegularCut } from "./svgs/regular/Web and Technology/RegularCut";
export { default as RegularDashboard } from "./svgs/regular/Web and Technology/RegularDashboard";
export { default as RegularDatabase } from "./svgs/regular/Web and Technology/RegularDatabase";
export { default as RegularDisplay } from "./svgs/regular/Web and Technology/RegularDisplay";
export { default as RegularDisplayAlt } from "./svgs/regular/Web and Technology/RegularDisplayAlt";
export { default as RegularDomain } from "./svgs/regular/Web and Technology/RegularDomain";
export { default as RegularDownload } from "./svgs/regular/Web and Technology/RegularDownload";
export { default as RegularEmptyFile } from "./svgs/regular/Web and Technology/RegularEmptyFile";
export { default as RegularFiles } from "./svgs/regular/Web and Technology/RegularFiles";
export { default as RegularFolder } from "./svgs/regular/Web and Technology/RegularFolder";
export { default as RegularGame } from "./svgs/regular/Web and Technology/RegularGame";
export { default as RegularHarddrive } from "./svgs/regular/Web and Technology/RegularHarddrive";
export { default as RegularHeadphone } from "./svgs/regular/Web and Technology/RegularHeadphone";
export { default as RegularImage } from "./svgs/regular/Web and Technology/RegularImage";
export { default as RegularKeyboard } from "./svgs/regular/Web and Technology/RegularKeyboard";
export { default as RegularLaptop } from "./svgs/regular/Web and Technology/RegularLaptop";
export { default as RegularLaptopPhone } from "./svgs/regular/Web and Technology/RegularLaptopPhone";
export { default as RegularLink } from "./svgs/regular/Web and Technology/RegularLink";
export { default as RegularMagnet } from "./svgs/regular/Web and Technology/RegularMagnet";
export { default as RegularMagnifier } from "./svgs/regular/Web and Technology/RegularMagnifier";
export { default as RegularMap } from "./svgs/regular/Web and Technology/RegularMap";
export { default as RegularMapMarker } from "./svgs/regular/Web and Technology/RegularMapMarker";
export { default as RegularMenu } from "./svgs/regular/Web and Technology/RegularMenu";
export { default as RegularMic } from "./svgs/regular/Web and Technology/RegularMic";
export { default as RegularMicrophone } from "./svgs/regular/Web and Technology/RegularMicrophone";
export { default as RegularMobile } from "./svgs/regular/Web and Technology/RegularMobile";
export { default as RegularMouse } from "./svgs/regular/Web and Technology/RegularMouse";
export { default as RegularPackage } from "./svgs/regular/Web and Technology/RegularPackage";
export { default as RegularPlug } from "./svgs/regular/Web and Technology/RegularPlug";
export { default as RegularPrinter } from "./svgs/regular/Web and Technology/RegularPrinter";
export { default as RegularReload } from "./svgs/regular/Web and Technology/RegularReload";
export { default as RegularRemoveFile } from "./svgs/regular/Web and Technology/RegularRemoveFile";
export { default as RegularRocket } from "./svgs/regular/Web and Technology/RegularRocket";
export { default as RegularRssFeed } from "./svgs/regular/Web and Technology/RegularRssFeed";
export { default as RegularSave } from "./svgs/regular/Web and Technology/RegularSave";
export { default as RegularScrollDown } from "./svgs/regular/Web and Technology/RegularScrollDown";
export { default as RegularSearch } from "./svgs/regular/Web and Technology/RegularSearch";
export { default as RegularSearchAlt } from "./svgs/regular/Web and Technology/RegularSearchAlt";
export { default as RegularShare } from "./svgs/regular/Web and Technology/RegularShare";
export { default as RegularShareAlt } from "./svgs/regular/Web and Technology/RegularShareAlt";
export { default as RegularShoppingBasket } from "./svgs/regular/Web and Technology/RegularShoppingBasket";
export { default as RegularShortcode } from "./svgs/regular/Web and Technology/RegularShortcode";
export { default as RegularSignal } from "./svgs/regular/Web and Technology/RegularSignal";
export { default as RegularStarEmpty } from "./svgs/regular/Web and Technology/RegularStarEmpty";
export { default as RegularStarFill } from "./svgs/regular/Web and Technology/RegularStarFill";
export { default as RegularStarHalf } from "./svgs/regular/Web and Technology/RegularStarHalf";
export { default as RegularTab } from "./svgs/regular/Web and Technology/RegularTab";
export { default as RegularTimer } from "./svgs/regular/Web and Technology/RegularTimer";
export { default as RegularTrashCan } from "./svgs/regular/Web and Technology/RegularTrashCan";
export { default as RegularUnlink } from "./svgs/regular/Web and Technology/RegularUnlink";
export { default as RegularUpload } from "./svgs/regular/Web and Technology/RegularUpload";
export { default as RegularUser } from "./svgs/regular/Web and Technology/RegularUser";
export { default as RegularUsers } from "./svgs/regular/Web and Technology/RegularUsers";
export { default as RegularWebsite } from "./svgs/regular/Web and Technology/RegularWebsite";
export { default as RegularWebsiteAlt } from "./svgs/regular/Web and Technology/RegularWebsiteAlt";
export { default as RegularZip } from "./svgs/regular/Web and Technology/RegularZip";
export { default as RegularZoomIn } from "./svgs/regular/Web and Technology/RegularZoomIn";
export { default as RegularZoomOut } from "./svgs/regular/Web and Technology/RegularZoomOut";
